language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script: 
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test